name: clearance
description: multi vendors categories


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.4+35

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.2.3
  flutter_screenutil: ^5.4.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  intl: ^0.17.0
  persistent_bottom_nav_bar: ^4.0.2
  smooth_page_indicator: ^1.0.0+2
  path_provider: ^2.0.11
  flutter_svg: ^0.23.0+1
  store_redirect: ^2.0.1
  file_picker: ^4.6.1
  page_transition: ^2.0.5
  shared_preferences: ^2.0.13
  permission_handler: ^10.2.0
  camera: ^0.10.4
  contacts_service: ^0.6.3
  conditional_builder_null_safety: ^0.0.6
  intl_phone_field: ^3.1.0
  carousel_slider: ^4.1.1
  mime_type: ^1.0.0
  uni_links: ^0.5.1
  dio: ^4.0.6
  lottie: ^1.2.2
  photo_view: ^0.13.0
  flutter_colorpicker: ^1.0.3
  flutter_cache_manager: ^3.3.0
  flutter_rating_bar: ^4.0.0
  flutter_html: ^2.2.1
  restart_app: ^1.1.0
  shimmer: ^2.0.0
  geolocator: ^9.0.1
  transparent_image: ^2.0.0
  cached_network_image: ^3.2.0
  like_button: ^2.0.4
  intl_phone_number_input: ^0.7.0+2
  bot_toast: ^4.0.3
  #  image_picker: ^0.8.5+3
  google_maps_flutter: ^2.1.6
  connectivity_plus: ^2.3.4
  top_modal_sheet: ^2.0.1
  badges: ^3.0.2
  modal_bottom_sheet: ^2.0.1
  filter_list: ^1.0.2
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.1.2
  country_pickers: ^2.0.0
  webview_flutter: ^2.0.4
  device_info_plus: ^4.0.0
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^9.7.0
  sign_in_with_apple: ^4.1.0
  firebase_auth: ^4.2.9
  flutter_countdown_timer: ^4.1.0
  pinput: ^2.2.31
  url_launcher: ^6.1.9
  fluttertoast: ^8.1.1
  firebase_analytics: ^10.1.4
  firebase_crashlytics: ^3.0.15
  #uni_links: ^0.5.1
  share_plus: ^4.5.3
  screenshot: ^1.2.3
  image_downloader: ^0.31.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/mainIcon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/mainIconAdaptive.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/testJson/
    - assets/images/
    - assets/images/account/
    - assets/images/public/
    - assets/images/errors/
    - assets/images/product_details/
    - assets/images/account/my_orders/
    - assets/icons/
    - assets/images/json/



  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf


